export const catBreedData = [
  { value: "페르시안", label: "페르시안" },
  { value: "샴", label: "샴" },
  { value: "메인쿤", label: "메인쿤" },
  { value: "래그돌", label: "래그돌" },
  { value: "스핑크스", label: "스핑크스" },
  { value: "벵갈", label: "벵갈" },
  { value: "브리티시 쇼트헤어", label: "브리티시 쇼트헤어" },
  { value: "스코티시 폴드", label: "스코티시 폴드" },
  { value: "러시안 블루", label: "러시안 블루" },
  { value: "아비시니안", label: "아비시니안" },
  { value: "아메리칸 쇼트헤어", label: "아메리칸 쇼트헤어" },
  { value: "오리엔탈 쇼트헤어", label: "오리엔탈 쇼트헤어" },
  { value: "버미즈", label: "버미즈" },
  { value: "노르웨이 숲 고양이", label: "노르웨이 숲 고양이" },
  { value: "시베리안", label: "시베리안" },
  { value: "샤르트뢰", label: "샤르트뢰" },
  { value: "터키시 앙고라", label: "터키시 앙고라" },
  { value: "이집션 마우", label: "이집션 마우" },
  { value: "코니시 렉스", label: "코니시 렉스" },
  { value: "재패니즈 밥테일", label: "재패니즈 밥테일" },
  { value: "맨스", label: "맨스" },
  { value: "버만", label: "버만" },
  { value: "봄베이", label: "봄베이" },
  { value: "히말라얀", label: "히말라얀" },
  { value: "코랏", label: "코랏" },
  { value: "싱가푸라", label: "싱가푸라" },
  { value: "톤키니즈", label: "톤키니즈" },
  { value: "셀커크 렉스", label: "셀커크 렉스" },
  { value: "픽시밥", label: "픽시밥" },
  { value: "캘리포니아 스팽글드", label: "캘리포니아 스팽글드" },
  { value: "세이셸루아", label: "세이셸루아" },
  { value: "라팜", label: "라팜" },
  { value: "스노우슈", label: "스노우슈" },
  { value: "오시캣", label: "오시캣" },
  { value: "소코케", label: "소코케" },
  { value: "투르크멘 고양이", label: "투르크멘 고양이" },
  { value: "아메리칸 컬", label: "아메리칸 컬" },
  { value: "아시안 고양이", label: "아시안 고양이" },
  { value: "제르맨 렉스", label: "제르맨 렉스" },
  { value: "믹스", label: "믹스" },
  { value: "먼치킨", label: "먼치킨" },
  { value: "터키시 반", label: "터키시 반" },
  { value: "하바나 브라운", label: "하바나 브라운" },
  { value: "발리니즈", label: "발리니즈" },
  { value: "드래곤 리", label: "드래곤 리" },
  { value: "피터볼드", label: "피터볼드" },
  { value: "사바나", label: "사바나" },
  { value: "스코티시 스트레이트", label: "스코티시 스트레이트" },
  { value: "오스트레일리안 미스트", label: "오스트레일리안 미스트" },
  { value: "데본 렉스", label: "데본 렉스" },
  { value: "우랄 렉스", label: "우랄 렉스" },
  { value: "캘리포니아 쇼트헤어", label: "캘리포니아 쇼트헤어" },
  { value: "시티스", label: "시티스" },
  { value: "요크 초콜릿", label: "요크 초콜릿" },
  { value: "스코티시 폴드 롱헤어", label: "스코티시 폴드 롱헤어" },
  { value: "캣츠미라", label: "캣츠미라" },
  { value: "라가머핀", label: "라가머핀" },
  { value: "헬렌 시암", label: "헬렌 시암" },
  { value: "세인트 버나드 캣", label: "세인트 버나드 캣" },
  { value: "저먼 포레스트 캣", label: "저먼 포레스트 캣" },
  { value: "하이랜더", label: "하이랜더" },
  { value: "믹스", label: "믹스" },
];

export const dogBreedData = [
  { value: "진돗개", label: "진돗개" },
  { value: "푸들", label: "푸들" },
  { value: "불독", label: "불독" },
  { value: "시츄", label: "시츄" },
  { value: "골든 리트리버", label: "골든 리트리버" },
  { value: "래브라도 리트리버", label: "래브라도 리트리버" },
  { value: "비글", label: "비글" },
  { value: "치와와", label: "치와와" },
  { value: "포메라니안", label: "포메라니안" },
  { value: "시베리안 허스키", label: "시베리안 허스키" },
  { value: "로트와일러", label: "로트와일러" },
  { value: "도베르만", label: "도베르만" },
  { value: "닥스훈트", label: "닥스훈트" },
  { value: "복서", label: "복서" },
  { value: "시바견", label: "시바견" },
  { value: "말티즈", label: "말티즈" },
  { value: "보더 콜리", label: "보더 콜리" },
  { value: "코커 스패니얼", label: "코커 스패니얼" },
  { value: "퍼그", label: "퍼그" },
  { value: "요크셔 테리어", label: "요크셔 테리어" },
  { value: "그레이트 데인", label: "그레이트 데인" },
  { value: "달마시안", label: "달마시안" },
  { value: "세인트 버나드", label: "세인트 버나드" },
  { value: "보스턴 테리어", label: "보스턴 테리어" },
  { value: "웰시 코기", label: "웰시 코기" },
  { value: "아키타", label: "아키타" },
  { value: "알래스칸 맬러뮤트", label: "알래스칸 맬러뮤트" },
  { value: "버니즈 마운틴 도그", label: "버니즈 마운틴 도그" },
  { value: "차우차우", label: "차우차우" },
  { value: "사모예드", label: "사모예드" },
  { value: "비즐라", label: "비즐라" },
  { value: "와이머라너", label: "와이머라너" },
  { value: "휘핏", label: "휘핏" },
  { value: "불 테리어", label: "불 테리어" },
  { value: "페키니즈", label: "페키니즈" },
  { value: "셰틀랜드 쉽독", label: "셰틀랜드 쉽독" },
  { value: "그레이트 피레니즈", label: "그레이트 피레니즈" },
  { value: "슈나우저", label: "슈나우저" },
  { value: "차이니즈 크레스티드", label: "차이니즈 크레스티드" },
  { value: "비숑 프리제", label: "비숑 프리제" },
  { value: "하바니즈", label: "하바니즈" },
  { value: "아이리시 세터", label: "아이리시 세터" },
  { value: "이탈리안 그레이하운드", label: "이탈리안 그레이하운드" },
  { value: "믹스", label: "믹스" },
  { value: "에어데일 테리어", label: "에어데일 테리어" },
  { value: "바셋 하운드", label: "바셋 하운드" },
  { value: "오스트레일리안 셰퍼드", label: "오스트레일리안 셰퍼드" },
  { value: "벨지안 말리노이즈", label: "벨지안 말리노이즈" },
  { value: "블러드하운드", label: "블러드하운드" },
  { value: "보더 테리어", label: "보더 테리어" },
  { value: "브리타니 스패니얼", label: "브리타니 스패니얼" },
  { value: "케언 테리어", label: "케언 테리어" },
  { value: "체서피크 베이 리트리버", label: "체서피크 베이 리트리버" },
  { value: "컬리 코티드 리트리버", label: "컬리 코티드 리트리버" },
  { value: "댄디 딘몬트 테리어", label: "댄디 딘몬트 테리어" },
  { value: "아이리시 테리어", label: "아이리시 테리어" },
  { value: "아이리시 울프하운드", label: "아이리시 울프하운드" },
  { value: "잭 러셀 테리어", label: "잭 러셀 테리어" },
  { value: "카발리에 킹 찰스 스패니얼", label: "카발리에 킹 찰스 스패니얼" },
  { value: "커커 스패니얼", label: "커커 스패니얼" },
  { value: "키슈", label: "키슈" },
  { value: "라사 압소", label: "라사 압소" },
  { value: "리틀 라이온 도그", label: "리틀 라이온 도그" },
  { value: "노르웨이 엘크하운드", label: "노르웨이 엘크하운드" },
  { value: "노리치 테리어", label: "노리치 테리어" },
  { value: "노퍽 테리어", label: "노퍽 테리어" },
  { value: "파피용", label: "파피용" },
  { value: "플랫 코티드 리트리버", label: "플랫 코티드 리트리버" },
  { value: "시저 키즈", label: "시저 키즈" },
  { value: "쇼트코티드 포인터", label: "쇼트코티드 포인터" },
  { value: "리트리버", label: "리트리버" },
  { value: "살루키", label: "살루키" },
  { value: "삼번", label: "삼번" },
  { value: "실리햄 테리어", label: "실리햄 테리어" },
  { value: "스카이 테리어", label: "스카이 테리어" },
  { value: "스태퍼드셔 불 테리어", label: "스태퍼드셔 불 테리어" },
  { value: "틸다 테리어", label: "틸다 테리어" },
  { value: "티베탄 테리어", label: "티베탄 테리어" },
  { value: "토이 테리어", label: "토이 테리어" },
  {
    value: "웨스트 하이랜드 화이트 테리어",
    label: "웨스트 하이랜드 화이트 테리어",
  },
  { value: "휘펫", label: "휘펫" },
  { value: "비어딧드 콜리", label: "비어딧드 콜리" },
  { value: "폴리쉬 롤랜드 쉽독", label: "폴리쉬 롤랜드 쉽독" },
];
