export const catBreedData = [
  { value: "페르시안", label: "페르시안" },
  { value: "샴", label: "샴" },
  { value: "메인쿤", label: "메인쿤" },
  { value: "래그돌", label: "래그돌" },
  { value: "스핑크스", label: "스핑크스" },
  { value: "벵갈", label: "벵갈" },
  { value: "브리티시 쇼트헤어", label: "브리티시 쇼트헤어" },
  { value: "스코티시 폴드", label: "스코티시 폴드" },
  { value: "러시안 블루", label: "러시안 블루" },
  { value: "아비시니안", label: "아비시니안" },
  { value: "아메리칸 쇼트헤어", label: "아메리칸 쇼트헤어" },
  { value: "오리엔탈 쇼트헤어", label: "오리엔탈 쇼트헤어" },
  { value: "버미즈", label: "버미즈" },
  { value: "노르웨이 숲 고양이", label: "노르웨이 숲 고양이" },
  { value: "시베리안", label: "시베리안" },
  { value: "샤르트뢰", label: "샤르트뢰" },
  { value: "터키시 앙고라", label: "터키시 앙고라" },
  { value: "이집션 마우", label: "이집션 마우" },
  { value: "코니시 렉스", label: "코니시 렉스" },
  { value: "재패니즈 밥테일", label: "재패니즈 밥테일" },
  { value: "맨스", label: "맨스" },
  { value: "버만", label: "버만" },
  { value: "봄베이", label: "봄베이" },
  { value: "히말라얀", label: "히말라얀" },
  { value: "코랏", label: "코랏" },
  { value: "싱가푸라", label: "싱가푸라" },
  { value: "톤키니즈", label: "톤키니즈" },
  { value: "셀커크 렉스", label: "셀커크 렉스" },
  { value: "픽시밥", label: "픽시밥" },
  { value: "캘리포니아 스팽글드", label: "캘리포니아 스팽글드" },
  { value: "세이셸루아", label: "세이셸루아" },
  { value: "라팜", label: "라팜" },
  { value: "스노우슈", label: "스노우슈" },
  { value: "오시캣", label: "오시캣" },
  { value: "소코케", label: "소코케" },
  { value: "투르크멘 고양이", label: "투르크멘 고양이" },
  { value: "아메리칸 컬", label: "아메리칸 컬" },
  { value: "아시안 고양이", label: "아시안 고양이" },
  { value: "제르맨 렉스", label: "제르맨 렉스" },
  { value: "믹스", label: "믹스" },
];
