export const dogBreedData = [
  { value: "진돗개", label: "진돗개" },
  { value: "푸들", label: "푸들" },
  { value: "불독", label: "불독" },
  { value: "시츄", label: "시츄" },
  { value: "골든 리트리버", label: "골든 리트리버" },
  { value: "래브라도 리트리버", label: "래브라도 리트리버" },
  { value: "비글", label: "비글" },
  { value: "치와와", label: "치와와" },
  { value: "포메라니안", label: "포메라니안" },
  { value: "시베리안 허스키", label: "시베리안 허스키" },
  { value: "로트와일러", label: "로트와일러" },
  { value: "도베르만", label: "도베르만" },
  { value: "닥스훈트", label: "닥스훈트" },
  { value: "복서", label: "복서" },
  { value: "시바견", label: "시바견" },
  { value: "말티즈", label: "말티즈" },
  { value: "보더 콜리", label: "보더 콜리" },
  { value: "코커 스패니얼", label: "코커 스패니얼" },
  { value: "퍼그", label: "퍼그" },
  { value: "요크셔 테리어", label: "요크셔 테리어" },
  { value: "그레이트 데인", label: "그레이트 데인" },
  { value: "달마시안", label: "달마시안" },
  { value: "세인트 버나드", label: "세인트 버나드" },
  { value: "보스턴 테리어", label: "보스턴 테리어" },
  { value: "웰시 코기", label: "웰시 코기" },
  { value: "아키타", label: "아키타" },
  { value: "알래스칸 맬러뮤트", label: "알래스칸 맬러뮤트" },
  { value: "버니즈 마운틴 도그", label: "버니즈 마운틴 도그" },
  { value: "차우차우", label: "차우차우" },
  { value: "사모예드", label: "사모예드" },
  { value: "비즐라", label: "비즐라" },
  { value: "와이머라너", label: "와이머라너" },
  { value: "휘핏", label: "휘핏" },
  { value: "불 테리어", label: "불 테리어" },
  { value: "페키니즈", label: "페키니즈" },
  { value: "셰틀랜드 쉽독", label: "셰틀랜드 쉽독" },
  { value: "그레이트 피레니즈", label: "그레이트 피레니즈" },
  { value: "슈나우저", label: "슈나우저" },
  { value: "차이니즈 크레스티드", label: "차이니즈 크레스티드" },
  { value: "비숑 프리제", label: "비숑 프리제" },
  { value: "하바니즈", label: "하바니즈" },
  { value: "아이리시 세터", label: "아이리시 세터" },
  { value: "이탈리안 그레이하운드", label: "이탈리안 그레이하운드" },
  { value: "믹스", label: "믹스" },
  { value: "에어데일 테리어", label: "에어데일 테리어" },
  { value: "바셋 하운드", label: "바셋 하운드" },
  { value: "오스트레일리안 셰퍼드", label: "오스트레일리안 셰퍼드" },
  { value: "벨지안 말리노이즈", label: "벨지안 말리노이즈" },
  { value: "블러드하운드", label: "블러드하운드" },
  { value: "보더 테리어", label: "보더 테리어" },
  { value: "브리타니 스패니얼", label: "브리타니 스패니얼" },
  { value: "케언 테리어", label: "케언 테리어" },
  { value: "체서피크 베이 리트리버", label: "체서피크 베이 리트리버" },
  { value: "컬리 코티드 리트리버", label: "컬리 코티드 리트리버" },
  { value: "댄디 딘몬트 테리어", label: "댄디 딘몬트 테리어" },
  { value: "아이리시 테리어", label: "아이리시 테리어" },
  { value: "아이리시 울프하운드", label: "아이리시 울프하운드" },
  { value: "잭 러셀 테리어", label: "잭 러셀 테리어" },
  { value: "카발리에 킹 찰스 스패니얼", label: "카발리에 킹 찰스 스패니얼" },
  { value: "커커 스패니얼", label: "커커 스패니얼" },
  { value: "키슈", label: "키슈" },
  { value: "라사 압소", label: "라사 압소" },
  { value: "리틀 라이온 도그", label: "리틀 라이온 도그" },
  { value: "노르웨이 엘크하운드", label: "노르웨이 엘크하운드" },
  { value: "노리치 테리어", label: "노리치 테리어" },
  { value: "노퍽 테리어", label: "노퍽 테리어" },
  { value: "파피용", label: "파피용" },
  { value: "플랫 코티드 리트리버", label: "플랫 코티드 리트리버" },
  { value: "시저 키즈", label: "시저 키즈" },
  { value: "쇼트코티드 포인터", label: "쇼트코티드 포인터" },
  { value: "리트리버", label: "리트리버" },
  { value: "살루키", label: "살루키" },
  { value: "삼번", label: "삼번" },
  { value: "실리햄 테리어", label: "실리햄 테리어" },
  { value: "스카이 테리어", label: "스카이 테리어" },
  { value: "스태퍼드셔 불 테리어", label: "스태퍼드셔 불 테리어" },
  { value: "틸다 테리어", label: "틸다 테리어" },
  { value: "티베탄 테리어", label: "티베탄 테리어" },
  { value: "토이 테리어", label: "토이 테리어" },
  {
    value: "웨스트 하이랜드 화이트 테리어",
    label: "웨스트 하이랜드 화이트 테리어",
  },
  { value: "휘펫", label: "휘펫" },
  { value: "비어딧드 콜리", label: "비어딧드 콜리" },
  { value: "폴리쉬 롤랜드 쉽독", label: "폴리쉬 롤랜드 쉽독" },
];
