export const POST_LIKE_STATUS = "POST_LIKE_STATUS";
export const POST_LIKE_COUNT = "POST_LIKE_COUNT";
export const POST_LIKED_BY_USER = "POST_LIKED_BY_USER";

export const COMMENT_LIKE_STATUS = "COMMENT_LIKE_STATUS";
export const COMMENT_LIKE_COUNT = "COMMENT_LIKE_COUNT";
